apiVersion: v1
kind: ServiceAccount
metadata:
  name: arkose-demo
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::541216676946:role/arkose-demo-single-wf-stage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: executor-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
  - kind: ServiceAccount
    name: arkose-demo
