apiVersion: builtin
kind: ConfigMapGenerator
behavior: create
metadata:
  name: dev-artifact-repositories
options:
  disableNameSuffixHash: true
  annotations:
    workflows.argoproj.io/default-artifact-repository: demo-s3
files:
  - demo-s3=artifact-repositories/demo-s3.yaml
