apiVersion: builtin
kind: ConfigMapGenerator
behavior: create
metadata:
  name: dev-artifacts
options:
  disableNameSuffixHash: true
  annotations:
    workflows.argoproj.io/default-artifact-repository: demo-s3
files:
  - demo-s3=artfacts/demo-s3-artifact.yaml
