apiVersion: builtin
kind: ConfigMapGenerator
behavior: create
metadata:
  name: dev-parameters
options:
  disableNameSuffixHash: true
  labels:
      workflows.argoproj.io/configmap-type: Parameter
literals:
- bucket=akuity-arkose-demo
- table-name=dev_statistics
- db-connection-secret=db-connection-dev
