apiVersion: v1
data:
  example-goodbye-s3: |
    s3:
      endpoint: s3.amazonaws.com
      bucket: example-bucket-name
      region: us-west-1
      useSDKCreds: true
      keyFormat: "prefix/goodbyes\
        /{{pod.name}}"
  example-hello-s3: |
    s3:
      endpoint: s3.amazonaws.com
      bucket: example-bucket-name
      region: us-west-1
      useSDKCreds: true
      keyFormat: "prefix/hellos\
        /{{pod.name}}"
kind: ConfigMap
metadata:
  name: example-artifact-repositories
---
apiVersion: v1
data:
  table-name: results
kind: ConfigMap
metadata:
  labels:
    workflows.argoproj.io/configmap-type: Parameter
  name: example-parameters
---
apiVersion: v1
data:
  DB_HOST: ZGIuaG9zdG5hbWU=
  DB_NAME: ZGF0YWJhc2VfbmFtZQ==
  DB_PASSWORD: c2VjcmV0UGFzc1cwcmQ=
  DB_PORT: MzYwMA==
  DB_USER: ZGF0YWJhc2VfdXNlcg==
kind: Secret
metadata:
  name: example-db-connect
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      auth: token
      replicas: 3
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: s3-new-files-sqs
spec:
  sqs:
    s3-new-files:
      jsonBody: true
      queue: my-fake-queue-2
      region: us-east-1
      waitTimeSeconds: 20
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  webhook:
    greet:
      endpoint: /greet
      method: POST
      port: "12000"
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aws-sqs
spec:
  dependencies:
  - eventName: example
    eventSourceName: s3-new-files-sqs
    name: sqs-dep
  triggers:
  - template:
      argoWorkflow:
        operation: submit
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body
            dependencyName: sqs-dep
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: goodbye-
            spec:
              workflowTemplateRef:
                name: goodbye-wf-template
      name: webhook-workflow-trigger
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  dependencies:
  - eventName: greet
    eventSourceName: webhook
    name: wh-dep
  triggers:
  - template:
      argoWorkflow:
        operation: submit
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body.names
            dependencyName: wh-dep
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: greet-
            spec:
              arguments:
                parameters:
                - name: names
                  value: to,be,replaced
              workflowTemplateRef:
                name: hello-wf-template
      name: webhook-workflow-trigger
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: goodbye-wf-template
spec:
  arguments:
    parameters:
    - name: cm-name
      value: default-cm
    - name: file
      value: ""
  artifactRepositoryRef:
    configMap: example-artifact-repositories
    key: example-goodbye-s3
  entrypoint: goodbye-wf
  templates:
  - arguments:
      parameters:
      - name: file
        value: '{{workflow.parameters.input-payload}}'
      - name: search
        value: hello
      - name: replace
        value: goodbye
    name: goodbye-wf
    template: replace-text
  - arguments:
      artifacts:
      - name: input-file
        path: /tmp/in.txt
        s3:
          key: '{{workflow.parameters.file}}'
      parameters:
      - name: search
        value: hello
      - name: replace
        value: goodbye
    container:
      args:
      - --input-file
      - /tmp/in.txt
      - --output-file
      - /tmp/out.txt
      - --search
      - '{{inputs.parameters.search}}'
      - --replace
      - '{{inputs.parameters.replace}}'
      command:
      - python
      - rt.py
      image: ghcr.io/nikita-akuity/replace-text:sha-1882e20
    name: replace-text
    outputs:
      artifacts:
      - name: output-file
        path: /tmp/out.txt
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-wf-template
spec:
  arguments:
    parameters:
    - name: names
      value: ""
  artifactRepositoryRef:
    configMap: example-artifact-repositories
    key: example-hello-s3
  entrypoint: hello-wf
  templates:
  - arguments:
      parameters:
      - name: greeting
        value: hello
      - default: '{{workflow.parameters.names}}'
        name: names
    container:
      args:
      - --names
      - '{{inputs.parameters.names}}'
      - --greeting
      - '{{inputs.parameters.greeting}}'
      - --output-file
      - /tmp/out.txt
      command:
      - python
      - greet.py
      image: ghcr.io/nikita-akuity/greetings:sha-1882e20
    name: greet
    outputs:
      artifacts:
      - archive:
          none: {}
        name: output-file
        path: /tmp/out.txt
