apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::541216676946:role/arkose-demo-single-wf-dev
  name: arkose-demo
---
apiVersion: v1
data:
  demo-s3: |
    s3:
      bucket: akuity-arkose-demo
      region: us-west-1
      useSDKCreds: true
      keyFormat: >-
        dev/
          {{workflow.creationTimestamp.Y}}-
          {{workflow.creationTimestamp.m}}-
          {{workflow.creationTimestamp.d}}/
        {{workflow.name}}
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: demo-s3
  name: dev-artifact-repositories
---
apiVersion: v1
data:
  table-name: dev_statistics
kind: ConfigMap
metadata:
  labels:
    workflows.argoproj.io/configmap-type: Parameter
  name: dev-parameters
---
apiVersion: v1
data:
  example-s3: |
    s3:
      bucket: example-bucket-name
      region: us-west-1
      useSDKCreds: true
      keyFormat: >-
        prefix/
          {{workflow.creationTimestamp.Y}}-
          {{workflow.creationTimestamp.m}}-
          {{workflow.creationTimestamp.d}}/
        {{workflow.name}}
kind: ConfigMap
metadata:
  annotations:
    workflows.argoproj.io/default-artifact-repository: example-s3
  name: example-artifacts
---
apiVersion: v1
data:
  db-connection-secret: example-db-connect
  table-name: results
kind: ConfigMap
metadata:
  labels:
    workflows.argoproj.io/configmap-type: Parameter
  name: example-parameters
---
apiVersion: v1
data:
  DB_HOST: ZGIuaG9zdG5hbWU=
  DB_NAME: ZGF0YWJhc2VfbmFtZQ==
  DB_PASSWORD: c2VjcmV0UGFzc1cwcmQ=
  DB_PORT: MzYwMA==
  DB_USER: ZGF0YWJhc2VfdXNlcg==
kind: Secret
metadata:
  name: example-db-connect
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
spec:
  nats:
    native:
      auth: token
      replicas: 3
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  webhook:
    greet-and-count:
      endpoint: /greet-and-count
      method: POST
      port: "12000"
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  dependencies:
  - eventName: greet-and-count
    eventSourceName: webhook
    name: wh-dep
  triggers:
  - template:
      argoWorkflow:
        operation: submit
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body
            dependencyName: wh-dep
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: greet-and-count-
            spec:
              workflowTemplateRef:
                name: single-wf-template
      name: webhook-workflow-trigger
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: container-templates
spec:
  templates:
  - container:
      args:
      - --names
      - '{{inputs.parameters.names}}'
      - --greeting
      - '{{inputs.parameters.greeting}}'
      - --output-file
      - /tmp/out.txt
      command:
      - python
      - greet.py
      image: ghcr.io/nikita-akuity/greetings:sha-1882e20
    inputs:
      parameters:
      - default: ""
        name: key-prefix
      - default: default
        name: greeting
      - default: Alice,Bob
        name: names
    name: greet
    outputs:
      artifacts:
      - name: output-file
        path: /tmp/out.txt
        s3:
          key: '{{pod.name}}.txt'
      parameters:
      - name: key
        value: '{{pod.name}}.txt'
  - container:
      args:
      - --input-file
      - /tmp/in.txt
      - --output-file
      - /tmp/out.txt
      - --search
      - '{{inputs.parameters.search}}'
      - --replace
      - '{{inputs.parameters.replace}}'
      command:
      - python
      - rt.py
      image: ghcr.io/nikita-akuity/replace-text:sha-1882e20
    inputs:
      artifacts:
      - name: input-file
        path: /tmp/in.txt
        s3:
          key: '{{inputs.parameters.input-key}}'
      parameters:
      - name: input-key
      - default: ""
        name: key-prefix
      - default: default
        name: search
      - default: default
        name: replace
    name: replace-text
    outputs:
      artifacts:
      - name: output-file
        path: /tmp/out.txt
        s3:
          key: '{{pod.name}}.txt'
      parameters:
      - name: key
        value: ' {{pod.name}}.txt'
  - container:
      args:
      - --input-file
      - /tmp/in.txt
      - --string
      - '{{inputs.parameters.string}}'
      - '>/tmp/result'
      - 2>/tmp/err.log
      command:
      - python
      - count.py
      image: ghcr.io/nikita-akuity/count:sha-1882e20
    inputs:
      artifacts:
      - name: input-file
        path: /tmp/in.txt
        s3:
          key: '{{inputs.parameters.input-key}}'
      parameters:
      - name: input-key
      - default: default
        name: string
    name: count
    outputs:
      parameters:
      - name: number
        valueFrom:
          default: "0"
          path: /tmp/result
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: script-templates
spec:
  templates:
  - inputs:
      parameters:
      - default: '["0","0","0"]'
        name: numbers
    name: sum
    script:
      command:
      - python
      image: python:3
      source: |
        import json
        numbers = json.loads('{{inputs.parameters.numbers}}')
        print(sum(map(int,numbers)))
  - inputs:
      artifacts:
      - name: sql
        path: /tmp/query.sql
        raw:
          data: |
            CREATE TABLE IF NOT EXISTS {{inputs.parameters.table-name}} (
              Id int NOT NULL AUTO_INCREMENT,
              WorkflowName varchar(255) NOT NULL,
              WorkflowDateTime datetime NOT NULL,
              SumHello int(32),
              SumGoodbye int(32),
              PRIMARY KEY (Id)
            );
            INSERT INTO {{inputs.parameters.table-name}} (WorkflowName, WorkflowDateTime, SumHello, SumGoodbye)
            VALUES (
              '{{workflow.name}}',
              '{{workflow.creationTimestamp.Y}}-{{workflow.creationTimestamp.m}}-{{workflow.creationTimestamp.d}} {{workflow.creationTimestamp.H}}:{{workflow.creationTimestamp.M}}:{{workflow.creationTimestamp.S}}',
              {{inputs.parameters.sum-hello}},
              {{inputs.parameters.sum-goodbye}}
            );
      parameters:
      - name: table-name
      - name: db-connection-secret
      - default: "NULL"
        name: sum-hello
      - default: "NULL"
        name: sum-goodbye
    name: write-to-db
    script:
      command:
      - bash
      envFrom:
      - secretRef:
          name: '{{inputs.parameters.db-connection-secret}}'
      image: mysql:8-debian
      source: |
        mysql --host=$DB_HOST --port=$DB_PORT --user=$DB_USER --password=$DB_PASSWORD $DB_NAME < /tmp/query.sql
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: single-wf-template
spec:
  arguments:
    parameters:
    - name: mysql-connection-secret
      value: db-connection-dev
    - name: cm-name
      value: dev-parameters
    - name: mysql-table-name
      valueFrom:
        configMapKeyRef:
          key: table-name
          name: dev-parameters
    - name: input-payload
      value: '[]'
  artifactRepositoryRef:
    configMap: dev-artifact-repositories
    key: demo-s3
  entrypoint: single-wf
  serviceAccountName: arkose-demo
  templates:
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: greeting
            value: hello
          - name: names
            value: '{{item}}'
        name: greetings
        templateRef:
          name: container-templates
          template: greet
        withParam: '{{workflow.parameters.input-payload}}'
      - arguments:
          parameters:
          - name: search
            value: hello
          - name: replace
            value: goodbye
          - name: input-key
            value: '{{item}}'
        depends: greetings
        name: goodbyes
        templateRef:
          name: container-templates
          template: replace-text
        withParam: '{{tasks.greetings.outputs.parameters.key}}'
      - arguments:
          parameters:
          - name: string
            value: hello
          - name: input-key
            value: '{{item}}'
        depends: greetings
        name: count-hellos
        templateRef:
          name: container-templates
          template: count
        withParam: '{{tasks.greetings.outputs.parameters.key}}'
      - arguments:
          parameters:
          - name: string
            value: goodbye
          - name: input-key
            value: '{{item}}'
        depends: goodbyes
        name: count-goodbyes
        templateRef:
          name: container-templates
          template: count
        withParam: '{{tasks.goodbyes.outputs.parameters.key}}'
      - arguments:
          parameters:
          - name: numbers
            value: '{{tasks.count-hellos.outputs.parameters.number}}'
        depends: count-hellos
        name: sum-hellos
        templateRef:
          name: script-templates
          template: sum
      - arguments:
          parameters:
          - name: numbers
            value: '{{tasks.count-goodbyes.outputs.parameters.number}}'
        depends: count-goodbyes
        name: sum-goodbyes
        templateRef:
          name: script-templates
          template: sum
      - arguments:
          parameters:
          - name: table-name
            valueFrom:
              configMapKeyRef:
                key: table-name
                name: '{{workflow.parameters.cm-name}}'
          - name: db-connection-secret
            valueFrom:
              configMapKeyRef:
                key: db-connection-secret
                name: '{{workflow.parameters.cm-name}}'
          - name: sum-hello
            value: '{{tasks.sum-hellos.outputs.result}}'
          - name: sum-goodbye
            value: '{{tasks.sum-goodbyes.outputs.result}}'
        depends: sum-hellos && sum-goodbyes
        name: write-result
        templateRef:
          name: script-templates
          template: write-to-db
    name: single-wf
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-connection-dev
spec:
  data:
  - remoteRef:
      key: arkose-demo/db/single-wf-dev
      property: host
    secretKey: DB_HOST
  - remoteRef:
      key: arkose-demo/db/single-wf-dev
      property: port
    secretKey: DB_PORT
  - remoteRef:
      key: arkose-demo/db/single-wf-dev
      property: database
    secretKey: DB_NAME
  - remoteRef:
      key: arkose-demo/db/single-wf-dev
      property: user
    secretKey: DB_USER
  - remoteRef:
      key: arkose-demo/db/single-wf-dev
      property: password
    secretKey: DB_PASSWORD
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: demo-db-connect
  target:
    name: db-connection-dev
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: demo-db-connect
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: arkose-demo
      region: us-west-1
      service: SecretsManager
