apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: count
  newName: ghcr.io/nikita-akuity/count
  newTag: sha-5a0f611
- name: greetings
  newName: ghcr.io/nikita-akuity/greetings
  newTag: sha-5a0f611
- name: replace-text
  newName: ghcr.io/nikita-akuity/replace-text
  newTag: sha-5a0f611
