apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: single-wf-template
spec:
  serviceAccountName: arkose-demo
  artifactRepositoryRef:
    configMap: dev-artifact-repositories
    key: demo-s3
  arguments:
    parameters:
    - {name: cm-name, value: dev-parameters}
