apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- secrets
- rbac

generators:
- generators/parameters.yaml
- generators/artifact-repositories.yaml

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_workflows_kustomize_schema.json

patchesStrategicMerge:
- argument-patch.yaml

images:
- name: count
  newName: ghcr.io/nikita-akuity/count
  newTag: sha-1882e20
- name: greetings
  newName: ghcr.io/nikita-akuity/greetings
  newTag: sha-1882e20
- name: replace-text
  newName: ghcr.io/nikita-akuity/replace-text
  newTag: sha-1882e20
