apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: start-pipeline
spec:
  template:
    serviceAccountName: operate-workflow-sa
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: count-all
spec:
  template:
    serviceAccountName: operate-workflow-sa
