apiVersion: builtin
kind: ConfigMapGenerator
behavior: create
metadata:
  name: dev-artifact-repositories
options:
  disableNameSuffixHash: true
files:
  - hello-s3=artifact-repositories/dev-hello-s3.yaml
  - goodbye-s3=artifact-repositories/dev-goodbye-s3.yaml
  - count-s3=artifact-repositories/dev-count-s3.yaml
