apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-wf-template
spec:
  serviceAccountName: arkose-demo
  artifactRepositoryRef:
    configMap: dev-artifact-repositories
    key: hello-s3
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: goodbye-wf-template
spec:
  serviceAccountName: arkose-demo
  artifactRepositoryRef:
    configMap: dev-artifact-repositories
    key: goodbye-s3
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: run-goodbyes-wf-template
spec:
  serviceAccountName: arkose-demo
  arguments:
    parameters:
    - name: bucket
      value: akuity-arkose-demo
    - name: prefix
      valueFrom:
        configMapKeyRef:
          name: dev-parameters
          key: hello-key-prefix
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: count-wf-template
spec:
  serviceAccountName: arkose-demo
  artifactRepositoryRef:
    configMap: dev-artifact-repositories
    key: count-s3
  arguments:
    parameters:
    - name: hello-key-prefix
      valueFrom:
        configMapKeyRef:
          name: dev-parameters
          key: hello-key-prefix
    - name: goodbye-key-prefix
      valueFrom:
        configMapKeyRef:
          name: dev-parameters
          key: goodbye-key-prefix
    - name: mysql-table-name
      valueFrom:
        configMapKeyRef:
          name: dev-parameters
          key: table-name
    - name: mysql-connection-secret
      value: db-connection-dev
