apiVersion: builtin
kind: ConfigMapGenerator
behavior: create
metadata:
  name: stage-parameters
options:
  disableNameSuffixHash: true
  labels:
      workflows.argoproj.io/configmap-type: Parameter
literals:
- table-name=stage_statistics
- hello-key-prefix=stage/many-wf/hellos
- goodbye-key-prefix=stage/many-wf/goodbyes
