apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- secrets
- rbac

generators:
- generators/stage-parameters.yaml
- generators/artifact-repositories.yaml

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json

patchesStrategicMerge:
- patches/wf-patch.yaml
- patches/sqs-patch.yaml

images:
- name: count
  newName: ghcr.io/nikita-akuity/count
  newTag: 0.1.0
- name: greetings
  newName: ghcr.io/nikita-akuity/greetings
  newTag: 0.1.0
- name: replace-text
  newName: ghcr.io/nikita-akuity/replace-text
  newTag: 0.1.0
