apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: demo-db-connect
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: arkose-demo
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-connection-stage
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: demo-db-connect
    kind: SecretStore
  target:
    name: db-connection-stage
  data:
  - secretKey: DB_HOST
    remoteRef:
      key: arkose-demo/db/many-wf-stage
      property: host
  - secretKey: DB_PORT
    remoteRef:
      key: arkose-demo/db/many-wf-stage
      property: port
  - secretKey: DB_NAME
    remoteRef:
      key: arkose-demo/db/many-wf-stage
      property: database
  - secretKey: DB_USER
    remoteRef:
      key: arkose-demo/db/many-wf-stage
      property: user
  - secretKey: DB_PASSWORD
    remoteRef:
      key: arkose-demo/db/many-wf-stage
      property: password
